Modules/Crm/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'dashboard'],function($e) {
    Route::get('brm','HomeController@index');
    Route::get('/', function () {
        return view('crm::home');
    })->name('crm.home');

    Auth::routes();

    Route::get('/home', 'HomeController@index')->name('home');

    $developerZones = \App\Models\Developer\Developer::all()->toArray();
    $controllers = \App\Models\Developer\Navigation::where('type','=','controller')->join('controllers','controllers.id','=','navigations.controller_id')->get()->toArray();

    Route::get('/', 'HomeController@index')->name('controllers');

    if(isset($controllers) && !empty($controllers)){
        foreach($controllers as $controller){
            if($controller['navigation']=='crm'){
                Route::get('/'.$controller['name'], $controller['controller'].'@'.$controller['function'])->prefix('crm')->name($controller['name']);
            }
            else{
                Route::get('/'.$controller['name'], $controller['controller'].'@'.$controller['function'])->prefix('loyalty')->name($controller['name']);
            }
        }
    }

    Route::prefix('loyalty')->group(function () {
        Route::resource('information','Loyalty\InformationController');
        Route::resource('sales','Loyalty\SalesController');
        Route::resource('loyaltyfronts','Loyalty\LoyaltyfrontController');
        Route::resource('benefits','Loyalty\BenefitController');
        Route::resource('offers','Loyalty\OffersController');
        Route::resource('categoryoffers','Loyalty\CategoryofferController');
        Route::resource('loyaltynavigations','Loyalty\LoyaltyNavigationController');
        Route::resource('subpages','Loyalty\SubpageController');
        Route::resource('galleries','Loyalty\GalleryController');
        Route::resource('images','Loyalty\ImageController');
    });

    Route::prefix('crm')->group(function(){
        Route::resource('users','Crm\UserController');
        Route::resource('customers','Crm\CustomerController');
        Route::resource('properties','Crm\PropertyController');
        Route::resource('propertycategories','Crm\PropertyCategoryController');
        Route::resource('customergroups','Crm\CustomerGroupController');
        Route::resource('loyaltyaccountsettings','Crm\LoyaltyAccountSettingController');
        Route::resource('filters','Crm\FilterController');
        Route::resource('newsletters','Crm\NewsletterController');
        Route::resource('logs','Crm\LogController');
        Route::resource('emails','Crm\EmailController');
        Route::resource('settings','Crm\CrmsettingsController');
        Route::resource('mailchimp','Crm\MailChimpController');
    });

    Route::prefix('cron')->group(function(){
        Route::get('chooseType/{type}','Cron\CronController@chooseType');
        Route::get('emailRecieved/{id}/{email_id}','Cron\CronController@emailRecieved')->name('emailRecieved');
    });

    Route::prefix('developer')->group(function () {
        Route::resource('permission','Developer\PermissionController');
        Route::resource('roles','Crm\RoleController');
        Route::resource('apideveloper','Developer\ApiDeveloperController');
    });

    if(isset($developerZones) && !empty($developerZones)){
        foreach($developerZones as $developerZone){
            Route::get('/'.$developerZone['name'], $developerZone['controller'].'@'.$developerZone['function'])->prefix('developer')->name($developerZone['name']);
        }
    }

    Route::get('/sync/{operator}','Crm\MailChimpController@sync')->name('mailchimp.sync');
    Route::get('/changeSubscribe/{id}/{operator}','Crm\MailChimpController@changeSubscribe')->name('mailchimp.changeSubscribe');

    Route::post('/store','Developer\NavigationController@store')->name('store');
    Route::post('/handleChangeOrder','Developer\NavigationController@handleChangeOrder')->name('handleChangeOrder');
    Route::post('/removeMenuItem','Developer\NavigationController@removeMenuItem')->name('removeMenuItem');
    Route::post('/editItem','Developer\NavigationController@editItem')->name('editItem');
    Route::post('/editProccess','Developer\NavigationController@editProccess')->name('editProccess');
    Route::post('roles/order','Crm\RoleController@reorder')->name('roles.order');

    Route::post('galleries.imagestore/{galleryID}','Loyalty\GalleryController@imagestore')->name('galleries.imagestore');
    Route::post('galleryChangeOrder','Loyalty\GalleryController@galleryChangeOrder')->name('galleryChangeOrder');
    Route::post('galleries.removeImage','Loyalty\GalleryController@removeImage')->name('galleries.removeImage');
    Route::post('galleries.changeActivity','Loyalty\GalleryController@changeActivity')->name('galleries.changeActivity');
    Route::post('galleries.changeActivityGallery','Loyalty\GalleryController@changeActivityGallery')->name('galleries.changeActivityGallery');
//navigation routes end

//controller routes start
    Route::post('/storeController','Developer\ControllersController@storeController')->name('storeController');
    Route::post('/removeController','Developer\ControllersController@removeController')->name('removeController');
    Route::post('/editController','Developer\ControllersController@editController')->name('editController');
    Route::post('/editItemController','Developer\ControllersController@editItemController')->name('editItemController');


    Route::post('/changeLang','BaseController@changeLang')->name('changeLang');
//controller routes end
//ajax
    Route::post('/handleChangeApiStatus','Developer\ApiDeveloperController@handleChangeApiStatus')->name('handleChangeApiStatus');
//endajax
    Route::post('/addPoints','Crm\CustomerController@addPoints')->name('addPoints');
    Route::post('/removePoints','Crm\CustomerController@removePoints')->name('removePoints');

    Route::post('/changeActivitySale','Loyalty\SalesController@changeActivitySale')->name('changeActivitySale');

    Route::post('/changeActivityCategoryoffer','Loyalty\CategoryofferController@changeActivityCategoryoffer')->name('changeActivityCategoryoffer');
    Route::post('/changeActivityoffer','Loyalty\OffersController@changeActivityoffer')->name('changeActivityoffer');
    Route::post('/changeActivityProperty','Crm\PropertyController@changeActivityProperty')->name('changeActivityProperty');

    Route::post('/changeActivityProfile','Crm\LoyaltyAccountSettingController@changeActivityProfile')->name('changeActivityProfile');
    Route::post('/changeSettingsForTypes','Crm\LoyaltyAccountSettingController@changeSettingsForTypes')->name('changeSettingsForTypes');

    Route::post('/customer_change_group','Crm\CustomerController@customer_change_group')->name('customer_change_group');

    Route::post('/change_default_group','Crm\CustomerGroupController@change_default_group')->name('change_default_group');

    Route::post('/navigationChangeOrder','Loyalty\LoyaltyNavigationController@navigationChangeOrder')->name('navigationChangeOrder');
    Route::post('/changeActivityNavigationLoyalty','Loyalty\LoyaltyNavigationController@changeActivityNavigationLoyalty')->name('changeActivityNavigationLoyalty');

});

Modules/Crm/Http/Controllers/Loyalty/CategoryofferController.php
<?php

namespace Modules\Crm\Http\Controllers\Loyalty;


use App\Libraries\LogLibrary;
use App\Models\Loyalty\CategoryOffer;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;
use Modules\Crm\Http\Controllers\BaseController;

class CategoryofferController extends BaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        parent::__construct();
    }


    public function index()
    {
        if ($this->loggedUser->can('categoryoffer.show')) {
            $response = CategoryOffer::where('deleted', '=', '0')->paginate(10);
            return view('crm::views.loyalty.categoryoffers.show')->with(array('categoryoffers' => $response));
        }
        else{
            Session::flash('permission','permissionMessage');
            return redirect()->route('home');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if ($this->loggedUser->can('categoryoffer.create')) {
            return view('crm::views.loyalty.categoryoffers.create');
        }
        else{
            Session::flash('permission','permissionMessage');
            return redirect()->route('home');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if ($this->loggedUser->can('categoryoffer.create')) {
            $log = new LogLibrary('CategoryofferController', 'store', Auth::user()->id, null, null, serialize($request->input()), null);
            $log->storeLog();

            $data = $request->all();

            $storeData = array(
                'internal_name' => $data['internal_name'],
                'active' => '1',
                'deleted' => '0',
                'created_at' => date('Y-m-d H:i:s'),
            );

            CategoryOffer::insert($storeData);

            return redirect(route('categoryoffer'));
        }
        else{
            Session::flash('permission','permissionMessage');
            return redirect()->route('home');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if ($this->loggedUser->can('categoryoffer.show')) {

        }
        else{
            Session::flash('permission','permissionMessage');
            return redirect()->route('home');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if ($this->loggedUser->can('categoryoffer.edit')) {
            $categoryoffer = CategoryOffer::find($id);
            return view('crm::views.loyalty.categoryoffers.edit')->with(array('categoryoffer' => $categoryoffer));
        }
        else{
            Session::flash('permission','permissionMessage');
            return redirect()->route('home');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if ($this->loggedUser->can('categoryoffer.edit')) {
            $log = new LogLibrary('CategoryofferController', 'update', Auth::user()->id, null, null, serialize($request->input()), serialize(CategoryOffer::find($id)));
            $log->storeLog();


            $data       = $request->all();
            $updateData = array(
                'internal_name' => $data['internal_name'],
            );

            CategoryOffer::where('id', '=', $id)->update($updateData);

            return redirect(route('categoryoffer'));
        }
        else{
            Session::flash('permission','permissionMessage');
            return redirect()->route('home');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if ($this->loggedUser->can('categoryoffer.delete')) {
            $log = new LogLibrary('CategoryofferController', 'destroy', Auth::user()->id, null, null, $id, null);
            $log->storeLog();

            $updateData = array(
                'deleted' => '1',
            );

            CategoryOffer::where('id', '=', $id)->update($updateData);

            return redirect(route('categoryoffer'));
        }
        else{
            Session::flash('permission','permissionMessage');
            return redirect()->route('home');
        }
    }

    public function changeActivityCategoryoffer(Request $request)
    {
        if ($this->loggedUser->can('categoryoffer.edit')) {
            $log = new LogLibrary('CategoryofferController', 'activity', Auth::user()->id, null, null, serialize($request->input()), null);
            $log->storeLog();

            $data = $request->all();

            $updateData = array(
                'active' => $data['value']
            );

            CategoryOffer::where('id', '=', $data['id'])->update($updateData);

            $response = array(
                'status' => '1'
            );

            echo json_encode($response);
        }
        else{
            Session::flash('permission','permissionMessage');
            return redirect()->route('home');
        }
    }
}

Modules/Crm/Resources/views/views/loyalty/categoryoffers/partials/table.blade.php
<style>
    .changeActivityCategoryOffer{
        cursor: pointer;
    }
</style>

@if(isset($categoryoffers) && !empty($categoryoffers))
    <table id="salesTable" class="table  table-striped table-bordered" style="width:100%">
        <thead>
        <tr>
            <th style="text-align: center;">#</th>
            <th style="text-align: center;">Interný názov kategórie</th>
            <th style="text-align: center;">Aktívna</th>
            <th style="text-align: center;">Akcie</th>
        </tr>
        </thead>
        <tbody>
        @foreach($categoryoffers as $categoryoffer)
            <tr>
                <td class="editContent" style="text-align: center;">{{$categoryoffer['id']}}</td>
                <td class="editContent" style="text-align: center;">{{$categoryoffer['internal_name']}}</td>
                <td class="editContent" data-type="showName" data-id="{{$categoryoffer['id']}}" style="text-align: center;">
                    @can('categoryoffer.edit')
                        <?=$categoryoffer['active'] == '1' ? '<span class="changeActivityCategoryOffer" data-id="'.$categoryoffer['id'].'"> <i class="icon-check active" style="color:darkgreen"></i></span>' : '<span class="changeActivityCategoryOffer" data-id="'.$categoryoffer['id'].'"><i class="icon-cross2 nonactive" style="color:darkred"></i></span>'?>
                    @endcan
                </td>
                <td style="text-align: center;">
                    @can('categoryoffer.edit')
                        <a href="{{route('categoryoffers.edit',['categoryoffer'=>$categoryoffer['id']])}}" class="editRow badge badge-primary" data-id="{{$categoryoffer['id']}}" style="cursor:pointer;margin-right:10px;">
                            Upraviť
                        </a>
                    @endcan
                    @can('categoryoffer.delete')
                        <form action="{{route('categoryoffers.destroy',['categoryoffer'=>$categoryoffer['id']])}}" method="POST" id="form_delete_{{$categoryoffer['id']}}" style="display: inline;">
                            @csrf
                            <input type="hidden" name="_method" value="DELETE">
                            <span class="deleteRow badge badge-danger" data-id="{{$categoryoffer['id']}}" style="cursor:pointer;">
                                    Vymazať
                                </span>
                        </form>
                    @endcan
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    <div class="row" style="margin-top:20px;">
        <div class="col-md-12">
            {{$categoryoffers->links()}}
        </div>
    </div>
@endif

<script>
    var getCheckedIcon = function(){
        var string = '<i class="icon-check active" style="color:darkgreen"></i></span>';
        return string
    }

    var getUncheckedIcon = function(){
        var string = '<i class="icon-cross2 nonactive" style="color:darkred"></i></span>';
        return string
    }

    var getSpinner = function(){
        var string = '<i class="spinner icon-spinner2" style="color:black"></i></span>';
        return string;
    }

    $('.deleteRow').on('click',function(){
        var id = $(this).data().id;
        Swal.fire({
            title:'Naozaj chcete zmazať túto kategóriu?',
            showCancelButton:true,
            cancelButtonText:'ODVOLAŤ',
            confirmButtonText:'ZMAZAŤ',
            confirmButtonColor:'darkred',
        }).then(function(response){
            if(response.value === true){
                $('#form_delete_'+id).submit();
            }
        });
    });

    $('.changeActivityCategoryOffer').on('click',function(){
        var $this = $(this);
        var value = '0';
        if($this.find('i').hasClass('icon-spinner2')){
            return;
        }
        else if($this.find('i').hasClass('active')){
            $this.html(getSpinner());
            value= '0';
            $.ajax({
                type: "POST",
                url: '{{route('changeActivityCategoryoffer')}}',
                data: {value:value,id:$this.data().id,_token:'{{csrf_token()}}'},
                dataType:'json',
                success:function(data){
                    if(data.status==='1'){
                        $this.html(getUncheckedIcon());
                    }
                }
            });
        }
        else{
            $this.html(getSpinner());
            value = 1;
            $.ajax({
                type: "POST",
                url: '{{route('changeActivityCategoryoffer')}}',
                data: {value:value,id:$this.data().id,_token:'{{csrf_token()}}'},
                dataType:'json',
                success:function(data){
                    if(data.status==='1'){
                        $this.html(getCheckedIcon());
                    }
                }
            });
        }
    });
</script>