Modules/Crm/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'dashboard'],function($e) {
    Route::get('brm','HomeController@index');
    Route::get('/', function () {
        return view('crm::home');
    })->name('crm.home');

    Auth::routes();

    Route::get('/home', 'HomeController@index')->name('home');

    $developerZones = \App\Models\Developer\Developer::all()->toArray();
    $controllers = \App\Models\Developer\Navigation::where('type','=','controller')->join('controllers','controllers.id','=','navigations.controller_id')->get()->toArray();

    Route::get('/', 'HomeController@index')->name('controllers');

    if(isset($controllers) && !empty($controllers)){
        foreach($controllers as $controller){
            if($controller['navigation']=='crm'){
                Route::get('/'.$controller['name'], $controller['controller'].'@'.$controller['function'])->prefix('crm')->name($controller['name']);
            }
            else{
                Route::get('/'.$controller['name'], $controller['controller'].'@'.$controller['function'])->prefix('loyalty')->name($controller['name']);
            }
        }
    }

    Route::prefix('loyalty')->group(function () {
        Route::resource('information','Loyalty\InformationController');
        Route::resource('sales','Loyalty\SalesController');
        Route::resource('loyaltyfronts','Loyalty\LoyaltyfrontController');
        Route::resource('benefits','Loyalty\BenefitController');
        Route::resource('offers','Loyalty\OffersController');
        Route::resource('categoryoffers','Loyalty\CategoryofferController');
        Route::resource('loyaltynavigations','Loyalty\LoyaltyNavigationController');
        Route::resource('subpages','Loyalty\SubpageController');
        Route::resource('galleries','Loyalty\GalleryController');
        Route::resource('images','Loyalty\ImageController');
    });

    Route::prefix('crm')->group(function(){
        Route::resource('users','Crm\UserController');
        Route::resource('customers','Crm\CustomerController');
        Route::resource('properties','Crm\PropertyController');
        Route::resource('propertycategories','Crm\PropertyCategoryController');
        Route::resource('customergroups','Crm\CustomerGroupController');
        Route::resource('loyaltyaccountsettings','Crm\LoyaltyAccountSettingController');
        Route::resource('filters','Crm\FilterController');
        Route::resource('newsletters','Crm\NewsletterController');
        Route::resource('logs','Crm\LogController');
        Route::resource('emails','Crm\EmailController');
        Route::resource('settings','Crm\CrmsettingsController');
        Route::resource('mailchimp','Crm\MailChimpController');
    });

    Route::prefix('cron')->group(function(){
        Route::get('chooseType/{type}','Cron\CronController@chooseType');
        Route::get('emailRecieved/{id}/{email_id}','Cron\CronController@emailRecieved')->name('emailRecieved');
    });

    Route::prefix('developer')->group(function () {
        Route::resource('permission','Developer\PermissionController');
        Route::resource('roles','Crm\RoleController');
        Route::resource('apideveloper','Developer\ApiDeveloperController');
    });

    if(isset($developerZones) && !empty($developerZones)){
        foreach($developerZones as $developerZone){
            Route::get('/'.$developerZone['name'], $developerZone['controller'].'@'.$developerZone['function'])->prefix('developer')->name($developerZone['name']);
        }
    }

    Route::get('/sync/{operator}','Crm\MailChimpController@sync')->name('mailchimp.sync');
    Route::get('/changeSubscribe/{id}/{operator}','Crm\MailChimpController@changeSubscribe')->name('mailchimp.changeSubscribe');

    Route::post('/store','Developer\NavigationController@store')->name('store');
    Route::post('/handleChangeOrder','Developer\NavigationController@handleChangeOrder')->name('handleChangeOrder');
    Route::post('/removeMenuItem','Developer\NavigationController@removeMenuItem')->name('removeMenuItem');
    Route::post('/editItem','Developer\NavigationController@editItem')->name('editItem');
    Route::post('/editProccess','Developer\NavigationController@editProccess')->name('editProccess');
    Route::post('roles/order','Crm\RoleController@reorder')->name('roles.order');

    Route::post('galleries.imagestore/{galleryID}','Loyalty\GalleryController@imagestore')->name('galleries.imagestore');
    Route::post('galleryChangeOrder','Loyalty\GalleryController@galleryChangeOrder')->name('galleryChangeOrder');
    Route::post('galleries.removeImage','Loyalty\GalleryController@removeImage')->name('galleries.removeImage');
    Route::post('galleries.changeActivity','Loyalty\GalleryController@changeActivity')->name('galleries.changeActivity');
    Route::post('galleries.changeActivityGallery','Loyalty\GalleryController@changeActivityGallery')->name('galleries.changeActivityGallery');
//navigation routes end

//controller routes start
    Route::post('/storeController','Developer\ControllersController@storeController')->name('storeController');
    Route::post('/removeController','Developer\ControllersController@removeController')->name('removeController');
    Route::post('/editController','Developer\ControllersController@editController')->name('editController');
    Route::post('/editItemController','Developer\ControllersController@editItemController')->name('editItemController');


    Route::post('/changeLang','BaseController@changeLang')->name('changeLang');
//controller routes end
//ajax
    Route::post('/handleChangeApiStatus','Developer\ApiDeveloperController@handleChangeApiStatus')->name('handleChangeApiStatus');
//endajax
    Route::post('/addPoints','Crm\CustomerController@addPoints')->name('addPoints');
    Route::post('/removePoints','Crm\CustomerController@removePoints')->name('removePoints');

    Route::post('/changeActivitySale','Loyalty\SalesController@changeActivitySale')->name('changeActivitySale');

    Route::post('/changeActivityCategoryoffer','Loyalty\CategoryofferController@changeActivityCategoryoffer')->name('changeActivityCategoryoffer');
    Route::post('/changeActivityoffer','Loyalty\OffersController@changeActivityoffer')->name('changeActivityoffer');
    Route::post('/changeActivityProperty','Crm\PropertyController@changeActivityProperty')->name('changeActivityProperty');

    Route::post('/changeActivityProfile','Crm\LoyaltyAccountSettingController@changeActivityProfile')->name('changeActivityProfile');
    Route::post('/changeSettingsForTypes','Crm\LoyaltyAccountSettingController@changeSettingsForTypes')->name('changeSettingsForTypes');

    Route::post('/customer_change_group','Crm\CustomerController@customer_change_group')->name('customer_change_group');

    Route::post('/change_default_group','Crm\CustomerGroupController@change_default_group')->name('change_default_group');

    Route::post('/navigationChangeOrder','Loyalty\LoyaltyNavigationController@navigationChangeOrder')->name('navigationChangeOrder');
    Route::post('/changeActivityNavigationLoyalty','Loyalty\LoyaltyNavigationController@changeActivityNavigationLoyalty')->name('changeActivityNavigationLoyalty');

});

Modules/Crm/Http/Controllers/Crm/PropertyCategoryController.php
<?php

namespace Modules\Crm\Http\Controllers\Crm;

use App\Http\Controllers\Controller;
use App\Libraries\LogLibrary;
use App\Models\Crm\PropertyCategory as Propertycategory;
use App\Models\Crm\PropertyCategoryLang as Propertycategorylang;
use App\Models\External\Language;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Str;
use Intervention\Image\Facades\Image;
use Modules\Crm\Http\Controllers\BaseController;

class PropertyCategoryController extends BaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        parent::__construct();
    }


    public function index()
    {
        if ($this->loggedUser->can('propertycategory.show')) {
            $propertycategories = Propertycategory::where('deleted', '=', '0')->paginate(10);
            return view('crm::views.admin.propertycategories')->with(array('propertycategories' => $propertycategories));
        }
        else{
            Session::flash('permission','permissionMessage');
            return redirect()->route('home');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if ($this->loggedUser->can('propertycategory.create')) {
            $languages = Language::all();
            return view('crm::views.admin.partials.propertycategories.create')->with(array('languages' => $languages));
        }
        else{
            Session::flash('permission','permissionMessage');
            return redirect()->route('home');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if ($this->loggedUser->can('propertycategory.create')) {
            $log = new LogLibrary('PropertyCategoryController', 'store', Auth::user()->id, null, null, serialize($request->input()), null);
            $log->storeLog();


            $data = $request->all();

            $insertData['image']         = '';
            $insertData['internal_name'] = $data['internal_name'];
            $insertData['created_at']    = date('Y-m-d H:i:s');

            if($request->cropper_used == '1'){
                if(!empty($request->cropper_value)) {

                    $base = $request->cropper_value;

                    $extension = explode(';', $base);
                    $extension = explode('/', $extension[0]);
                    $extension = $extension[1];

                    $imageName = uniqid() . '_' . time() . '.' . $extension;

                    $base64Str = substr($base, strpos($base, ",") + 1);
                    $image_base     = base64_decode($base64Str);

                    $destinationPath = public_path('images/categories');
                    $img3            = Image::make($image_base);
                    $img3->encode('jpeg', '75')->save($destinationPath . '/' . $imageName);

                    $insertData['image'] = $imageName;
                }
            }
            elseif ($request->hasFile('image')) {
                $image               = $request->file('image');
                $insertData['image'] = uniqid() . '_' . time() . '.' . $image->extension();

                $destinationPath = public_path('images/categories');
                if (!is_dir($destinationPath)) {
                    mkdir($destinationPath, 0777, true);
                    chmod($destinationPath, 0777);
                }

                $img = Image::make($image->path());
                $img->encode('jpeg', '75')->save($destinationPath . '/' . $insertData['image']);
            }

            $categoryID = Propertycategory::insertGetId($insertData);

            //langs
            if (isset($data['title']) && !empty($data['title'])) {
                foreach ($data['title'] as $lang => $title) {
                    if (!is_null($data['title'][$lang])) {
                        $insertLang = array(
                            'property_category_id' => $categoryID,
                            'code' => $lang,
                            'title' => $data['title'][$lang],
                            'short_description' => $data['short_description'][$lang],
                            'long_description' => $data['long_description'][$lang],
                            'slug' => isset($data['slug'][$lang]) && !empty($data['slug'][$lang]) ? Str::slug($data['slug'][$lang]) : Str::slug($data['title'][$lang]),
                            'created_at' => date('Y-m-d H:i:s')
                        );

                        Propertycategorylang::insert($insertLang);
                    }
                }
            }

            return redirect(route('propertycategory'));
        }
        else{
            Session::flash('permission','permissionMessage');
            return redirect()->route('home');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if ($this->loggedUser->can('propertycategory.show')) {

        }
        else{
            Session::flash('permission','permissionMessage');
            return redirect()->route('home');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if ($this->loggedUser->can('propertycategory.edit')) {
            $languages = Language::all();

            $propertycategories = Propertycategory::where('property_categories.id', '=', $id)->leftJoin('property_category_langs', 'property_categories.id', '=', 'property_category_langs.property_category_id')->get();

            $response = array();
            if (!empty($propertycategories)) {
                foreach ($propertycategories as $pc) {
                    $response['image']                          = $pc['image'];
                    $response['internal_name']                  = $pc['internal_name'];
                    $response['slug'][$pc['code']]              = $pc['slug'];
                    $response['title'][$pc['code']]             = $pc['title'];
                    $response['short_description'][$pc['code']] = $pc['short_description'];
                    $response['long_description'][$pc['code']]  = $pc['long_description'];

                }
            }

            return view('crm::views.admin.partials.propertycategories.edit')->with(array('languages' => $languages, 'id' => $id, 'propertycategory' => $response));
        }
        else{
            Session::flash('permission','permissionMessage');
            return redirect()->route('home');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if ($this->loggedUser->can('propertycategory.edit')) {
            $propertycategories = Propertycategory::where('property_categories.id', '=', $id)->leftJoin('property_category_langs', 'property_categories.id', '=', 'property_category_langs.property_category_id')->get();

            $response = array();
            if (!empty($propertycategories)) {
                foreach ($propertycategories as $pc) {
                    $response['image']                          = $pc['image'];
                    $response['internal_name']                  = $pc['internal_name'];
                    $response['slug'][$pc['code']]              = $pc['slug'];
                    $response['title'][$pc['code']]             = $pc['title'];
                    $response['short_description'][$pc['code']] = $pc['short_description'];
                    $response['long_description'][$pc['code']]  = $pc['long_description'];

                }
            }

            $log = new LogLibrary('PropertyCategoryController', 'update', Auth::user()->id, null, null, serialize($request->input()), serialize($response));
            $log->storeLog();


            $data = $request->all();


            $oldCategory                  = Propertycategory::find($id);
            $oldCategory['image']         = $data['old_image'];
            $oldCategory['internal_name'] = $data['internal_name'];
            $oldCategory['updated_at']    = date('Y-m-d H:i:s');

            $destinationPath = public_path('images/categories');

            if (isset($data['removeOldImage']) && !empty($data['removeOldImage'])) {
                if (isset($data['oldImage']) && !empty($data['oldImage'])) {
                    File::delete($destinationPath . '/' . $data['oldImage']);
                }
            }

            if($request->cropper_used == '1'){
                if(!empty($request->cropper_value)) {

                    $base = $request->cropper_value;

                    $extension = explode(';', $base);
                    $extension = explode('/', $extension[0]);
                    $extension = $extension[1];

                    $imageName = uniqid() . '_' . time() . '.' . $extension;

                    $base64Str = substr($base, strpos($base, ",") + 1);
                    $image_base     = base64_decode($base64Str);

                    $destinationPath = public_path('images/categories');
                    $img            = Image::make($image_base);
                    $img->encode('jpeg', '75')->save($destinationPath . '/' . $imageName);

                    $oldCategory['image'] = $imageName;
                }
            }
            else if ($request->hasFile('image')) {

Modules/Crm/Resources/views/views/admin/partials/propertycategories/create.blade.php
@extends('crm::layouts.master')

@section('content')
    <style>
        .languages{
            display:none;
        }
        .lang_sk{
            display:block;
        }

        .imageWrapper{
            width:100%;
            min-height:200px;
            background-repeat: no-repeat;
            background-size: cover;
            background-position:center;
        }
    </style>

    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.15/dist/summernote.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.15/dist/summernote.min.js"></script>

    <div class="row" style="margin-bottom:10px;">
        <div class="col-md-9"></div>
        <div class="col-md-3">
            <select class="form-control" id="languageChanger">
                @if(isset($languages) && !empty($languages))
                    @foreach($languages as $language)
                        <option value="{{$language['lang_code']}}">{{__('global.'.$language['lang_name'])}}</option>
                    @endforeach
                @endif
            </select>
        </div>
    </div>
    <div class="card" style="margin:0 auto;">
        <div class="card-header">
            <h5>
                Vytvorenie novej kategórie zariadení
            </h5>
        </div>
        <div class="card-body">
            <form action="{{route('propertycategories.store')}}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="row">
                    @if(isset($languages) && !empty($languages))
                        @foreach($languages as $language)
                            <div class="col-md-4 languages lang_{{$language['lang_code']}}">
                                <div class="form-group">
                                    <label>Názov kategórie v jazyku {{mb_strtolower(__('global.'.$language['lang_name']))}}</label>
                                    <input type="text" name="title[{{$language['lang_code']}}]" placeholder="Názov" class="form-control">
                                </div>
                            </div>
                        @endforeach
                    @endif
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>Interný názov</label>
                            <input type="text" name="internal_name" placeholder="Interný názov" class="form-control">
                        </div>
                    </div>
                        @if(isset($languages) && !empty($languages))
                            @foreach($languages as $language)
                                <div class="col-md-4 languages lang_{{$language['lang_code']}}">
                                    <label>Slug v jazyku {{__('global.'.$language['lang_name'])}}</label>
                                    <input type="text" name="slug[{{$language['lang_code']}}]" placeholder="Slug" class="form-control">
                                </div>
                            @endforeach
                        @endif
                    <legend></legend>
                        @if(isset($languages) && !empty($languages))
                            @foreach($languages as $language)
                                <div class="col-md-6 languages lang_{{$language['lang_code']}}">
                                    <div class="form-group">
                                        <label>Krátky popis v jazyku {{mb_strtolower(__('global.'.$language['lang_name']))}}</label>
                                        <input type="text" name="short_description[{{$language['lang_code']}}]" placeholder="Krátky popis" class="form-control">
                                    </div>
                                </div>
                                <div class="col-md-6 languages lang_{{$language['lang_code']}}">
                                    <div class="form-group">
                                        <label>Dlhý popis v jazyku {{mb_strtolower(__('global.'.$language['lang_name']))}}</label>
                                        <textarea type="text" name="long_description[{{$language['lang_code']}}]" class="form-control summernote"></textarea>
                                    </div>
                                </div>
                            @endforeach
                        @endif
                </div>
                <legend></legend>
                <div class="row">
                    <div class="col-md-6">
                        <div class="imageWrapper"></div>
                    </div>
                    <div class="col-md-6">
                        <div class="row">
                            <div class="col-md-12">
                                <button type="button" class="btn btn-info w100 btn-changeimg">Pridať/zmeniť obrázok</button>
                            </div>
                            <legend></legend>
                            <div class="col-md-12">
                                <button type="button" class="btn btn-success cropImageButton" style="width: 100%; {{isset($offer['img']) && !empty($offer['img']) ? '' : 'display:none;'}}">Orezať obrázok</button>
                            </div>
                            <legend></legend>
                            <div class="col-md-12">
                                <button type="button" class="btn btn-danger w100 mt10 btn-removeImage">Zmazať obrázok</button>
                            </div>
                            <input type="file" name="image" id="img" style="display:none;">
                        </div>
                    </div>
                </div>

                <input type="hidden" name="cropper_used" value="0">
                <input type="hidden" name="cropper_value" value="">


                <legend></legend>
                <button class="btn btn-primary btn-custom">Uložiť</button>
            </form>
        </div>
    </div>

    <div class="modal fade" id="cropper" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document" style="min-width: 80% !important;">
            <div class="modal-content">
                <div class="modal-body">
                    @include('crm::views.partials.cropper.cropper')
                </div>
            </div>
        </div>
    </div>

    <script>
        $('.summernote').summernote();

        $('.btn-changeimg').on('click',function(){
           $('#img').click();
        });

        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('[name="cropper_used"]').val('0');
                    $('[name="cropper_value"]').val('');
                    $('#image').attr('src',e.target.result);
                    $('.imageWrapper').css('background-image','url('+e.target.result+')');
                    $('.cropImageButton').show();
                }
                reader.readAsDataURL(input.files[0]);
            }
        }

        $('.cropImageButton').on('click',function(){
            $('#cropper').modal();
            setTimeout(function(){
                makeClickable()
            },500);
        });

        var makeClickable = function(){
            $(document).find('.aspectSixteenClickable').click();
        }

        $('.btn-removeImage').on('click',function(){
            $('#img').val('');
            $('[name="cropper_used"]').val('0');
            $('[name="cropper_value"]').val('');
            $('.imageWrapper').removeAttr('style');
        });

        $('#img').on('change',function(e){
            e.preventDefault();
            e.stopPropagation();
            readURL(this);
        });

        $('#languageChanger').on('change',function(){
           $('.languages').hide();
           $('.lang_'+$(this).val()).show();
        });
    </script>
@endsection

Modules/Crm/Resources/views/views/admin/partials/propertycategories/table.blade.php
<div class="table-responsive">
    @if(isset($propertycategories) && !empty($propertycategories))
    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th style="text-align: center;">#</th>
            <th style="text-align: center;">Interný názov</th>
            <th style="text-align: center;">Akcia</th>
        </tr>
        </thead>
        <tbody>
            @foreach($propertycategories as $property)
                <tr>
                    <td style="text-align: center;">{{$property['id']}}</td>
                    <td style="text-align: center;">{{$property['internal_name']}}</td>
                    <td style="text-align: center;">
                        @can('propertycategory.edit')
                            <a href="{{route('propertycategories.edit',['propertycategory'=>$property['id']])}}"><span class="badge badge-primary" style="cursor:pointer;">Upraviť</span></a>
                        @endcan
                        @can('propertycategory.delete')
                            <form action="{{route('propertycategories.destroy',['propertycategory'=>$property['id']])}}" method="post" style="display:inline" id="formDestroy_{{$property['id']}}">
                                @csrf
                                {{method_field('delete')}}
                                <span class="badge badge-danger confirmDestroy" data-id="{{$property['id']}}" style="cursor:pointer;">Zmazať</span>
                            </form>
                        @endcan
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
    {{$propertycategories->links()}}
    @endif
</div>

<script>
    $('.confirmDestroy').on('click',function(){
        var id = $(this).data().id;
        Swal.fire({
            title:'Naozaj chcete zmazať túto kategóriu?',
            showCancelButton:true,
            cancelButtonText:'ODVOLAŤ',
            confirmButtonText:'ZMAZAŤ',
            confirmButtonColor:'darkred',
        }).then(function(response){
            if(response.value === true){
                $('#formDestroy_'+id).submit();
            }
        });
    });
</script>