Modules/Crm/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'dashboard'],function($e) {
    Route::get('brm','HomeController@index');
    Route::get('/', function () {
        return view('crm::home');
    })->name('crm.home');

    Auth::routes();

    Route::get('/home', 'HomeController@index')->name('home');

    $developerZones = \App\Models\Developer\Developer::all()->toArray();
    $controllers = \App\Models\Developer\Navigation::where('type','=','controller')->join('controllers','controllers.id','=','navigations.controller_id')->get()->toArray();

    Route::get('/', 'HomeController@index')->name('controllers');

    if(isset($controllers) && !empty($controllers)){
        foreach($controllers as $controller){
            if($controller['navigation']=='crm'){
                Route::get('/'.$controller['name'], $controller['controller'].'@'.$controller['function'])->prefix('crm')->name($controller['name']);
            }
            else{
                Route::get('/'.$controller['name'], $controller['controller'].'@'.$controller['function'])->prefix('loyalty')->name($controller['name']);
            }
        }
    }

    Route::prefix('loyalty')->group(function () {
        Route::resource('information','Loyalty\InformationController');
        Route::resource('sales','Loyalty\SalesController');
        Route::resource('loyaltyfronts','Loyalty\LoyaltyfrontController');
        Route::resource('benefits','Loyalty\BenefitController');
        Route::resource('offers','Loyalty\OffersController');
        Route::resource('categoryoffers','Loyalty\CategoryofferController');
        Route::resource('loyaltynavigations','Loyalty\LoyaltyNavigationController');
        Route::resource('subpages','Loyalty\SubpageController');
        Route::resource('galleries','Loyalty\GalleryController');
        Route::resource('images','Loyalty\ImageController');
    });

    Route::prefix('crm')->group(function(){
        Route::resource('users','Crm\UserController');
        Route::resource('customers','Crm\CustomerController');
        Route::resource('properties','Crm\PropertyController');
        Route::resource('propertycategories','Crm\PropertyCategoryController');
        Route::resource('customergroups','Crm\CustomerGroupController');
        Route::resource('loyaltyaccountsettings','Crm\LoyaltyAccountSettingController');
        Route::resource('filters','Crm\FilterController');
        Route::resource('newsletters','Crm\NewsletterController');
        Route::resource('logs','Crm\LogController');
        Route::resource('emails','Crm\EmailController');
        Route::resource('settings','Crm\CrmsettingsController');
        Route::resource('mailchimp','Crm\MailChimpController');
    });

    Route::prefix('cron')->group(function(){
        Route::get('chooseType/{type}','Cron\CronController@chooseType');
        Route::get('emailRecieved/{id}/{email_id}','Cron\CronController@emailRecieved')->name('emailRecieved');
    });

    Route::prefix('developer')->group(function () {
        Route::resource('permission','Developer\PermissionController');
        Route::resource('roles','Crm\RoleController');
        Route::resource('apideveloper','Developer\ApiDeveloperController');
    });

    if(isset($developerZones) && !empty($developerZones)){
        foreach($developerZones as $developerZone){
            Route::get('/'.$developerZone['name'], $developerZone['controller'].'@'.$developerZone['function'])->prefix('developer')->name($developerZone['name']);
        }
    }

    Route::get('/sync/{operator}','Crm\MailChimpController@sync')->name('mailchimp.sync');
    Route::get('/changeSubscribe/{id}/{operator}','Crm\MailChimpController@changeSubscribe')->name('mailchimp.changeSubscribe');

    Route::post('/store','Developer\NavigationController@store')->name('store');
    Route::post('/handleChangeOrder','Developer\NavigationController@handleChangeOrder')->name('handleChangeOrder');
    Route::post('/removeMenuItem','Developer\NavigationController@removeMenuItem')->name('removeMenuItem');
    Route::post('/editItem','Developer\NavigationController@editItem')->name('editItem');
    Route::post('/editProccess','Developer\NavigationController@editProccess')->name('editProccess');
    Route::post('roles/order','Crm\RoleController@reorder')->name('roles.order');

    Route::post('galleries.imagestore/{galleryID}','Loyalty\GalleryController@imagestore')->name('galleries.imagestore');
    Route::post('galleryChangeOrder','Loyalty\GalleryController@galleryChangeOrder')->name('galleryChangeOrder');
    Route::post('galleries.removeImage','Loyalty\GalleryController@removeImage')->name('galleries.removeImage');
    Route::post('galleries.changeActivity','Loyalty\GalleryController@changeActivity')->name('galleries.changeActivity');
    Route::post('galleries.changeActivityGallery','Loyalty\GalleryController@changeActivityGallery')->name('galleries.changeActivityGallery');
//navigation routes end

//controller routes start
    Route::post('/storeController','Developer\ControllersController@storeController')->name('storeController');
    Route::post('/removeController','Developer\ControllersController@removeController')->name('removeController');
    Route::post('/editController','Developer\ControllersController@editController')->name('editController');
    Route::post('/editItemController','Developer\ControllersController@editItemController')->name('editItemController');


    Route::post('/changeLang','BaseController@changeLang')->name('changeLang');
//controller routes end
//ajax
    Route::post('/handleChangeApiStatus','Developer\ApiDeveloperController@handleChangeApiStatus')->name('handleChangeApiStatus');
//endajax
    Route::post('/addPoints','Crm\CustomerController@addPoints')->name('addPoints');
    Route::post('/removePoints','Crm\CustomerController@removePoints')->name('removePoints');

    Route::post('/changeActivitySale','Loyalty\SalesController@changeActivitySale')->name('changeActivitySale');

    Route::post('/changeActivityCategoryoffer','Loyalty\CategoryofferController@changeActivityCategoryoffer')->name('changeActivityCategoryoffer');
    Route::post('/changeActivityoffer','Loyalty\OffersController@changeActivityoffer')->name('changeActivityoffer');
    Route::post('/changeActivityProperty','Crm\PropertyController@changeActivityProperty')->name('changeActivityProperty');

    Route::post('/changeActivityProfile','Crm\LoyaltyAccountSettingController@changeActivityProfile')->name('changeActivityProfile');
    Route::post('/changeSettingsForTypes','Crm\LoyaltyAccountSettingController@changeSettingsForTypes')->name('changeSettingsForTypes');

    Route::post('/customer_change_group','Crm\CustomerController@customer_change_group')->name('customer_change_group');

    Route::post('/change_default_group','Crm\CustomerGroupController@change_default_group')->name('change_default_group');

    Route::post('/navigationChangeOrder','Loyalty\LoyaltyNavigationController@navigationChangeOrder')->name('navigationChangeOrder');
    Route::post('/changeActivityNavigationLoyalty','Loyalty\LoyaltyNavigationController@changeActivityNavigationLoyalty')->name('changeActivityNavigationLoyalty');

});

Modules/Crm/Http/Controllers/Crm/UserController.php
<?php

namespace Modules\Crm\Http\Controllers\Crm;

use App\Libraries\LogLibrary;
use App\Models\External\ModelHasRole;
use Illuminate\Http\Request;
use App\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Session;
use Modules\Crm\Http\Controllers\BaseController;
use Spatie\Permission\Models\Role;

class UserController extends BaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        parent::__construct();
    }


    public function index(Request $request)
    {
        if ($this->loggedUser->can('user.show')) {

            $userRoles = ModelHasRole::where('model_id','=',$this->loggedUser->id)
                ->join('roles as r','r.id','=','model_has_roles.role_id')
                ->orderBy('r.role_order','asc')
                ->get();

            $max_role = 0;
            if(!empty($userRoles)){
                $userRoles = $userRoles->toArray();
                $max_role = last($userRoles)['role_order'];
            }

            $users = User::select('users.*','r.name as roleName','r.id as roleID','r.role_order as roleOrder')
                ->orderBy('r.role_order', 'asc')
                ->leftJoin('model_has_roles as mhr','mhr.model_id','=','users.id')
                ->leftJoin('roles as r','r.id','=','mhr.role_id')
                ->get();

            $response = array();
            if(!empty($users)){
                foreach($users as $u){
                    $response[$u['id']]['id'] = $u['id'];
                    $response[$u['id']]['email'] = $u['email'];
                    $response[$u['id']]['name'] = $u['name'];
                    $response[$u['id']]['created_at'] = $u['created_at'];
                    $response[$u['id']]['roles_names'][$u['roleID']] = $u['roleName'];
                    $response[$u['id']]['roles_ids'][$u['roleID']] = $u['roleID'];
                    $response[$u['id']]['roles_order'][$u['roleID']] = $u['roleOrder'];
                }
            }

            return view('crm::views.admin.users', ['users'=>$response,'max_role'=>$max_role]);
        }
        else{
            Session::flash('permission','permissionMessage');
            return redirect()->route('home');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if ($this->loggedUser->can('user.create')) {

            $userRoles = ModelHasRole::where('model_id','=',$this->loggedUser->id)
                ->join('roles as r','r.id','=','model_has_roles.role_id')
                ->orderBy('r.role_order','asc')
                ->get();

            $max_role = 0;
            if(!empty($userRoles)){
                $userRoles = $userRoles->toArray();
                $max_role = last($userRoles)['role_order'];
            }

            $roles = Role::orderBy('role_order','asc')->where('role_order','<=',$max_role)->get();

            return view('crm::views.admin.partials.users.create',['roles'=>$roles,'max_role'=>$max_role]);
        }
        else{
            Session::flash('permission','permissionMessage');
            return redirect()->route('home');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if ($this->loggedUser->can('user.create')) {
            $log = new LogLibrary('UserController', 'store', Auth::user()->id, null, null, serialize($request->input()));
            $log->storeLog();


            $this->validate($request, [
                'name' => 'required',
                'email' => 'required|email|unique:users,email',
                'password' => 'required|same:confirm-password',
            ]);

            $input             = $request->all();
            $input['password'] = Hash::make($input['password']);

            $user = User::create($input);
            $user->assignRole($request->input('roles'));

            return redirect()->route('users.index')
                ->with('success', 'User created successfully');
        }
        else{
            Session::flash('permission','permissionMessage');
            return redirect()->route('home');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if ($this->loggedUser->can('user.show')) {
            $user = User::find($id);
            return view('crm::users.show', compact('user'));
        }
        else{
            Session::flash('permission','permissionMessage');
            return redirect()->route('home');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if ($this->loggedUser->can('user.edit')) {
            $user     = User::find($id);

            $userRolesExtend = ModelHasRole::where('model_id','=',$id)
                ->join('roles as r','r.id','=','model_has_roles.role_id')
                ->orderBy('r.role_order','asc')
                ->get();

            //dd($userRolesExtend);

            $userRoles = ModelHasRole::where('model_id','=',$this->loggedUser->id)
                ->join('roles as r','r.id','=','model_has_roles.role_id')
                ->orderBy('r.role_order','asc')
                ->get();

            $userRole = array();
            $max_role = 0;
            if(!empty($userRoles)){
                $userRoles = $userRoles->toArray();
                foreach($userRoles as $userR){
                    $userRole[] = $userR['role_id'];
                }
                $max_role = last($userRoles)['role_order'];

                $userRolesExtend = $userRolesExtend->toArray();

                if(last($userRolesExtend)['role_order']>$max_role){
                    return redirect()->route('home');
                }
            }



            $roles = Role::orderBy('role_order','asc')->where('role_order','<=',$max_role)->get();


            return view('crm::views.admin.partials.users.edit', compact('user', 'roles', 'userRole','max_role'));
        }
        else{
            Session::flash('permission','permissionMessage');
            return redirect()->route('home');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if ($this->loggedUser->can('user.edit')) {
            $user = User::find($id);

            $log = new LogLibrary('UserController', 'update', Auth::user()->id, null, null, serialize($request->input()), serialize($user));
            $log->storeLog();

            $this->validate($request, [
                'name' => 'required',
            ]);

            $input = $request->all();

            $user = User::find($id);
            $user->update($input);

            ModelHasRole::where('model_id', $id)->delete();

            $user->assignRole($request->input('roles'));

            return redirect()->route('users.index')
                ->with('success', 'User updated successfully');
        }
        else{
            Session::flash('permission','permissionMessage');
            return redirect()->route('home');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if ($this->loggedUser->can('user.delete')) {
            $log = new LogLibrary('UserController', 'destroy', Auth::user()->id, null, null, $id, null);
            $log->storeLog();

            User::find($id)->delete();
            return redirect()->route('users.index')
                ->with('success', 'User deleted successfully');
        }
        else{
            Session::flash('permission','permissionMessage');
            return redirect()->route('home');
        }
    }
}

Modules/Crm/Resources/views/views/admin/partials/users/create.blade.php
@extends('crm::layouts.master')

@section('content')
    <style>
        ul li {
            list-style-type:none;
        }
    </style>
    <div class="card" style="width:60%;margin: 0 auto;">
        <div class="card-header">
            <h5>Vytvorenie užívateľa</h5>
        </div>
        <div class="card-body">
            <form action="{{route('users.store')}}" method="post">
                @csrf
                <div class="form-group">
                    <label for="" class="form-label">Meno</label>
                    <input type="text" name="name" class="form-control" placeholder="Meno a priezvisko">
                </div>
                <div class="form-group">
                    <label for="" class="form-label">Email</label>
                    <input type="text" name="email" class="form-control" placeholder="Email">
                </div>
                <div class="form-group">
                    <label for="" class="form-label">Heslo</label>
                    <input type="password" name="password" class="form-control" placeholder="Heslo">
                </div>
                <div class="form-group">
                    <label for="" class="form-label">Heslo</label>
                    <input type="password" name="confirm-password" class="form-control" placeholder="Potvrdenie hesla">
                </div>
                <legend></legend>

                @if(isset($roles) && !empty($roles))
                    <h5>Rola</h5>
                    <ul>
                    @foreach($roles as $key => $role)
                        <li>
                            <label for="">
                                <input type="checkbox" name="roles[]" value="{{$role['id']}}">
                                {{$role['name']}}
                            </label>
                        </li>
                    @endforeach
                    </ul>
                @endif
                <legend></legend>
                <button class="btn btn-primary btn-custom">Vytvoriť</button>
            </form>
        </div>
    </div>
@endsection

Modules/Crm/Resources/views/views/admin/partials/users/edit.blade.php
@extends('crm::layouts.master')

@section('content')
    <style>
        ul li {
            list-style-type:none;
        }
    </style>
    <div class="card" style="width:60%;margin: 0 auto;">
        <div class="card-header">
            <h5>Úprava užívateľa</h5>
        </div>
        <div class="card-body">
            <form action="{{route('users.update',['user'=>$user->id])}}" method="post">
                {{ method_field('PUT') }}
                @csrf
                <input type="hidden" name="id" value="{{$user->id}}">
                <div class="form-group">
                    <label for="" class="form-label">Meno</label>
                    <input type="text" name="name" value="{{$user->name}}" class="form-control" placeholder="Meno a priezvisko">
                </div>
                <div class="form-group">
                    <label for="" class="form-label">Email</label>
                    <input type="text" name="email" value="{{$user->email}}" disabled class="form-control" placeholder="Email">
                </div>
                <input type="hidden" name="old-password" value="{{$user->password}}">
                <legend></legend>

                @if(isset($roles) && !empty($roles))
                    <h5>Rola</h5>
                    <ul>
                        @foreach($roles as $key => $role)
                            <li>
                                <label for="">
                                    <input type="checkbox" {{(in_array($role['id'],$userRole)) ? 'checked' : ''}} name="roles[]" value="{{$role['id']}}">
                                    {{$role['name']}}
                                </label>
                            </li>
                        @endforeach
                    </ul>
                @endif
                <legend></legend>
                <button class="btn btn-primary btn-custom">Upraviť</button>
            </form>
        </div>
    </div>
@endsection

Modules/Crm/Resources/views/views/admin/partials/users/userTable.blade.php
<style>
    .dataTables_paginate {
        margin-top: 10px;
    }
</style>

<table id="userTable" class="table  table-striped table-bordered" style="width:100%">
    <thead>
    <tr>
        <th style="text-align: center;">#</th>
        <th style="text-align: center;">Meno</th>
        <th style="text-align: center;">E-mail</th>
        <th style="text-align: center;">Rola</th>
        <th style="text-align: center;">Zaregistrovaný</th>
        <th style="text-align: center;">Akcie</th>
    </tr>
    </thead>
    <tbody>
    @if(isset($users) && !empty($users))
        @foreach($users as $user)
        <tr>
            <td style="text-align: center;">{{$user['id']}}</td>
            <td class="editContent" data-type="show_name" data-id="{{$user['id']}}" style="text-align: center;">{{$user['name']}}</td>
            <td class="editContent" data-type="name" data-id="{{$user['id']}}" style="text-align: center;">{{$user['email']}}</td>
            <td class="editContent" data-type="name" data-id="{{$user['id']}}" style="text-align: center;">{{isset($user['roles_names']) && !empty($user['roles_names']) ? implode(', ',$user['roles_names']) : ''}}</td>
            <td class="editContent" data-type="controller" data-id="{{$user['id']}}" style="text-align:center;">{{date('d.m.Y H:i:s',strtotime($user['created_at']))}}</td>
            <td style="text-align: center;">
                @if(isset($user['roles_order']) && !empty($user['roles_order']) && last($user['roles_order'])<=$max_role)
                    @can('user.edit')
                    <a href="{{route('users.edit',['user'=>$user['id']])}}" class="editRow badge badge-primary" data-id="{{$user['id']}}" style="cursor:pointer;margin-right:10px;">
                        Upraviť
                    </a>
                    @endcan
                    @can('user.delete')
                        <form action="{{route('users.destroy',['user'=>$user['id']])}}" style="display:inline" id="user_form_delete_{{$user['id']}}" method="post">
                            @csrf
                            @method('DELETE')
                            <span class="deleteRow badge badge-danger" data-id="{{$user['id']}}" style="cursor:pointer;">
                                Vymazať
                            </span>
                        </form>
                    @endcan
                @else
                    <small>Nemáš právomoc na editáciu</small>
                @endif
            </td>
        </tr>
        @endforeach
    @endif
    </tbody>
</table>

<script>
    $('.deleteRow').on('click',function(){
       var id = $(this).data().id;
        Swal.fire({
            title:'Naozaj chcete zmazať tohto užívateľa?',
            showCancelButton:true,
            cancelButtonText:'ODVOLAŤ',
            confirmButtonText:'ZMAZAŤ',
            confirmButtonColor:'darkred',
        }).then(function(response){
            if(response.value === true){
                $('#user_form_delete_'+id).submit();
            }
        });
    });
</script>